apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: wsc2025
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 950274644703.dkr.ecr.ap-northeast-1.amazonaws.com/app-repo:v1.0.0
        ports:
        - containerPort: 80
